### PR TITLE
implemented y variation which varies the y offset of custom objects.

### PR DESCRIPTION
**Pull request by sijmenvb**
I implemented y variation for the vertical offset of custom objects. it is accessible as a 4th "spinner"  in the offset menu. 

as an example if the y variation is 20 the offset will be randomly 10 lower or higher than the actual offset.
when the offset is odd it will move down. so if the variation is 1 it the object will either spawn at the original height or one lower.
this is because for trees moving them into the ground is often better than moving them up.

this feature can be used to have trees of slightly varying heights on a flat surfaces without needing extra schematics.
it is also very useful for more advanced techniques such as: placing ore schematics, making caves with schematics, floating islands clouds or balloons.
it can also be uses to scatter schematics on cliff faces.

previously this was only possible by adding the same schematic multiple times and varying the offset for each schematic. i had to do this once and it is **very** tedious.

I tested behavior near height limit and near 0, and tested loading and saving layers which all work fine.

### CODE REVIEW

**Comment by sijmenvb** [comment]
just finished testing this for version 2.9.4 and it works like a charm for making 1.18 caves.

**Comment by Captain-Chaos** [comment]
I'm working on this now. I want to combine this with other changes and implement it differently, so I won't be using the pull request and I'll close it now. But I will ensure that it is backwards compatible with your change so that layers that you and others might have created using this feature will continue to work. Let me know if there are any problems with that, once the next release comes out!

Thank you for the work you put in and the inspiration for this feature!

**Comment by Captain-Chaos** [comment]
Here is my implementation, in case you're interested or want to provide feedback: https://github.com/Captain-Chaos/WorldPainter/commit/748e2c9212155e9eb45f344a5b740b97c0d845be

**Comment by sijmenvb** [comment]
i'm definitely interested, and it looks like a vary similar implementation which I'm happy with. one issue I ran into while testing is that if you want to use this technique to add rocks to super steep cliffs. effectively adding in (small) overhangs, the problem occurs where even at a density of 1 the rocks can look quite sparse on the cliff. and it is quite annoying to duplicate the layer and add it multiple times. so an option to set the density to more than one schematic per block could be nice.

on another note.
my next idea for helping this same cliff placement is a way to align schematics with the slope. so i can e.g. make a tree that hangs out of a cliff and then near the "random rotation" button it would have a align with slope option where you can choose which direction of the schematic you want to align with the slope (e.g. positive x, negative z, etc. (maybe even diagonal for diagonally build schematics)) and then the schematic would be rotated depending on the slope at that point so it would always face away from the cliff. and I'm pretty sure this could also be helpful when doing other stuff. (placing stairs comes to mind)
and for determining the slope angle you can simply look at the four surrounding blocks. (maybe add special case for flat ground where it's random)
might try to implement this myself but wont have time for this for a while. let me know what you think.

**Comment by Captain-Chaos** [comment]
I see what you mean about the rotated objects on steep slopes. That's more niche and less easy to solve though. Feel free to file an enhancement ticket if you can come up with a simple and elegant solution for that, which I think will be a challenge.

**Pull request closed without merging**
