### PR TITLE
Create a task system (Fixes #26)

### LINKED ISSUE #26: Indroduce a Task System in WorldPainter
My proposal for WorldPainter is to implement a task system, where a tasks are created, and run one after the other. I believe WorldPainter should have this because of this important reason:
- Terraformers constantly have to deal with large maps (10000+ x 10000+), and therefore operations such as global operations because increasingly slow. The task system can make it so that the user (terraformer) can specify as many global operations as they want while their first operation is being processed. Then the task manager executes the tasks one by one in order. This could be a massive time saver for terraformers as they could specify multiple global operations (or other operations), and all of the specified operations will be executed one after the other.

I have started the creation of the `TaskManager` and `Task class`, and I will be making a pull request soon. I would appreciate it if no changes are made to WorldPainter for a day, so I could make a pull request WITHOUT CONFLICTS. (I still don't know how to resolve conflicts).

I would appreciate if feedback and improvements could be made on this, as I think it could make for a easier user experience. My currently progress is on my fork of WorldPainter.

### PR DESCRIPTION
**Pull request by frogocomics**
My proposal for WorldPainter is to implement a task system, where a tasks are created, and run one after the other. I believe WorldPainter should have this because of this important reason:

- Terraformers constantly have to deal with large maps (10000+ x 10000+), and therefore operations such as global operations because increasingly slow. The task system can make it so that the user (terraformer) can specify as many global operations as they want while their first operation is being processed. Then the task manager executes the tasks one by one in order. This could be a massive time saver for terraformers as they could specify multiple global operations (or other operations), and all of the specified operations will be executed one after the other.

I've created a task system where task types and the names of the tasks can be specified for preview on the WorldEdit gui. This task system should be fully functional, and should be integrated into some core WorldPainter classes. There are two types of tasks, `UserTask` and `BackgroundTask`. User tasks run ONE after the OTHER. Background tasks run all at once.

Below is an example on how to create and execute a task.
```
public void example() throws InterruptedException {
        //Lets create a task
        UserTask task = new UserTask(new Thread(() -> {
            //Task logic here
        }), "Example Task", TaskTypes.CUSTOM);
        task.addToQueue();
        TaskManager.runAll();
    }
```

### CODE REVIEW

**Comment by frogocomics** [comment]
Fixes #26

**Comment by frogocomics** [comment]
Update: I found a Job manager already in WorldPainter. It appears as if it is unused code.

**Comment by Captain-Chaos** [comment]
Interesting. If I understand you correctly, the problem you're trying to solve is that people working on large maps frequently have to perform multiple global operations and right now have to wait for each one to be finished before they can start the next. Right? I can see that it could be useful to do something about that.

Before you get to deep into an implementation, we should first think about what the functionality should be exactly, and if it would actually be useful enough to be worthwhile. The actual total time of the operations would not change, as they still have to be performed one after the other. The main advantage is that the user could queue them all up at once and could then leave the computer unattended for longer. Is that also the main advantage you see or am I misinterpreting your proposal?

I wonder if it might not be more useful to do such operations using one or more scripts, and if that is not possible because of current limitations on scripting, work on those. And/or I wonder if it might be a good idea to look into parallelising the global operations so that they take less time by taking advantage of multiple cores.

**Comment by Captain-Chaos** [comment]
Do you want me to critique your code? I see some flaws with it that would prevent me from accepting it as is even if we agreed this was the right direction for a solution.

Have you implemented anything in the GUI yet which makes use of this code?

**Comment by frogocomics** [comment]
No not yet. The gui part should be simple as it should just say something like "Running global operations task" or something like that. I actually don't understand how to work with Swing, I'm a man of JavaFx

**Comment by frogocomics** [comment]
Yes, I want my code to be critiqued

**Comment by frogocomics** [comment]
There are two types of tasks, `UserTask`s and `BackgroundTask`s. Usertasks do not allow multithreading, since global operations might sometimes require a specific order, but background tasks run all at once. I don't know what flaws there are in my code, but I assume there are some, since I'm not too good of a programmer (I was self taught)

**Comment by frogocomics** [comment]
I'm really sorry, but I'll be away for about 24 - 36 hrs due to flight. I gave you access on my fork, so feel free to fix whatever you feel is bad.

**Comment by Captain-Chaos** [comment]
Honestly it sounds like all this would be much better suited to scripting. It already allows you to import masks, etc. and I could add any missing functionality. Are you writing this code for someone else, or are you the one creating these worlds? I'm willing to answer any questions you might have about how to achieve things using a script.

**Comment by frogocomics** [comment]
I'm writing the code for myself. No, I don't know how to script.

**Comment by Captain-Chaos** [comment]
Do you want to try it? I could help. If you give me a basic workflow I can give you a script which would perform the same actions. The scripts are in JavaScript (by default; other languages are possible too if you so desire), so it shouldn't be hard to learn for you. For starters, see [here](http://www.worldpainter.net/trac/wiki/Scripting) and http://www.worldpainter.net/trac/wiki/Scripting/API.

**Comment by Captain-Chaos** [comment]
If you'd rather pursue this, that's fine too. I'll help, but I can't guarantee I'll merge it into WorldPainter.

**Comment by frogocomics** [comment]
I'm actually more interesting in plugins, and I want to see more WorldPainter plugin devs..

**Comment by frogocomics** [comment]
Is there any documentation for plugin making? Once I get into plugin making, I guess I can make improvements to the current WorldPainter plugin system.

**Comment by Captain-Chaos** [comment]
You can create plugins, but you can't currently distribute them, as WorldPainter will only load plugins signed by me. It's a security and quality control measure. I haven't yet signed any plugins (besides the ancient demo one I made myself years ago), and there has been next to no interest from developers, but perhaps it is time to start doing that.

There is no documentation for creating plugins yet, but it's pretty easy:

1. Create a separate module for your plugin, which depends on WPGUI
1. Create a subclass of `AbstractPlugin`
1. Make it implement one or more of `LayerProvider`, `CustomLayerProvider`, `LayerEditorProvider` or `OperationProvider`
1. Create a file called `org.pepsoft.worldpainter.plugins` in the root of your plugin module's classpath
1. In it, place a single line containing the fully qualified class name of your plugin class
1. Add the plugin module to the runtime classpath of WorldPainter

Ordinarily you would place the plugin jar in WorldPainter's plugins directory instead of that last step, but that will only work if it is signed by me. If and when you wanted to distribute the plugin you would need to build a jar and get it signed by me. Since I'm not doing that yet we'd have to work out a procedure when it came to that.

**Comment by Captain-Chaos** [comment]
A LayerProvider would provide single instance layers; non-customisable layers of which there is only one instance and for which a fixed button would be added to the Layers panel, like the default layers. These layers currently can't have customisable settings.

A CustomLayerProvider provides multi-instance, configurable layers; these are added to the + button menu on the layer panels to allow the user to create as many instances as they like.

A LayerEditorProvider provides the graphical editor panel components with which the custom layers it provides can be configured.

An OperationProvider provides tools or operations, which will be added to the Tools panel. Take a look at the various abstract classes and interfaces in the Operation interface's class hierarchy for examples of various kinds of operations and which base classes will help you implement them.

This is all a work in progress and not meant to be finished or comprehensive, so feel free to suggest modifications or additions if you want to be able to use plugins to modify other aspects of WorldPainter!

**Comment by Captain-Chaos** [comment]
Haven't heard from you in a while. Are you still interested in pursuing this, or shall I close the pull request?

**Comment by frogocomics** [comment]
I don't know to be honest. I think this should be kept in WorldPainter,
just in case, and could be removed anytime.

**Comment by Captain-Chaos** [comment]
It's not in WorldPainter yet. ;) I think I'll close it for now, as there is quite enough unused stuff in WorldPainter already to begin with. It won't go away so if ever you want to pick it up again feel free to contact me!

**Pull request closed without merging**
