### PR TITLE
(Untested) Working scripting API for JAVA 15

### PR DESCRIPTION
**Pull request by MattiBorchers**
Migration from Nashorn to GraalVM JavaScript
For more info, see here: https://golb.hplar.ch/2020/04/java-javascript-engine.html

### CODE REVIEW

**Comment by Captain-Chaos** [comment]
Thanks! GraalVM claims to be compatible with JSR 223; are the code changes actually necessary? Won't it just be registered as a JavaScript scripting engine and just work?

**Comment by MattiBorchers** [comment]
I tried to install GraalVM using this method: https://www.graalvm.org/docs/getting-started/windows/ , but this alone wont work, because I still get these error:

unexptected_error_1

I also had to change the "JavaHome" variable in the registry path: "Computer\HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\JDK\17.0.1" to my GraalVM directory.

Now I get a different error message:

error_2

Perhaps the whole scripting thing is not so trivial after all.

This is my cmd showing the following infos for the Java Version:
```java -version
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05, mixed mode, sharing)

js -version
GraalVM JavaScript (GraalVM CE Native 21.3.0)
```

**Comment by Captain-Chaos** [comment]
I don't think you need to use the VM itself, just the JavaScript library. Doesn't it work if you keep the pom changes, but not the code changes?

**Comment by Captain-Chaos** [comment]
The next release of WorldPainter will include the GraalVM JavaScript engine. Thanks for your help with this!

**Pull request closed without merging**
